config/routes.rb
Rails.application.routes.draw do
  root 'waypoints#index'
  resources :waypoints
  resources :vehicles

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    has_many :waypoints
end

app/models/waypoint.rb
class Waypoint < ApplicationRecord
    belongs_to :vehicle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:vehicle_name)
    end
end

app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController
  before_action :set_waypoint, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /waypoints
  # GET /waypoints.json
  def index
    @waypoints = Waypoint.all
    @vehicles = Vehicle.all
  end

  # GET /waypoints/1
  # GET /waypoints/1.json
  def show
  end

  # GET /waypoints/new
  def new
    @waypoint = Waypoint.new
    @vehicles = Vehicle.all

    respond_to do |format|
      format.html # new.html.erb 
      format.xml { render :xml => @waypoint } 
    end
  end

  # GET /waypoints/1/edit
  def edit
    @waypoint = Waypoint.find(params[:id])
    @vehicles = Vehicle.all
  end

  # POST /waypoints
  # POST /waypoints.json
  def create
    # @waypoint = Waypoint.new(waypoint_params)

    if Vehicle.exists?(vehicle_name: params[:vehicle_identifier])
      puts "Vehicle exist"
      @vehicle = Vehicle.find_by(vehicle_name: params[:vehicle_identifier])
    else
      puts "Vehicle doesn't exist"
      @vehicle = Vehicle.new(:vehicle_name => params[:vehicle_identifier])
      @vehicle.save
    end

    @waypoint = Waypoint.new({:latitude => params[:latitude], :longitude => params[:longitude], :sent_at => params[:sent_at], :vehicle_id => @vehicle.id})

    respond_to do |format|
      if @waypoint.save
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully created.' }
        format.json { render :show, status: :created, location: @waypoint }
      else
        format.html { render :new }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waypoints/1
  # PATCH/PUT /waypoints/1.json
  def update
    respond_to do |format|
      if @waypoint.update(waypoint_params)
        format.html { redirect_to @waypoint, notice: 'Waypoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @waypoint }
      else
        format.html { render :edit }
        format.json { render json: @waypoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waypoints/1
  # DELETE /waypoints/1.json
  def destroy
    @waypoint.destroy
    respond_to do |format|
      format.html { redirect_to waypoints_url, notice: 'Waypoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waypoint
      @waypoint = Waypoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waypoint_params
      params.require(:waypoint).permit(:latitude, :longitude, :sent_at, :vehicle_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/waypoints_helper.rb
module WaypointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gps</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- OpenLayers's CSS -->
    <link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css" type="text/css">
    <!-- OpenLayers's JS -->
    <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>

    <!-- Bootstrap's CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Bootstrap's JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Material Icons's CSS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
  </head>

  <!--<nav class="navbar">
    <div class="">
    </div>
  </nav>-->

  <div class="container">
    <body>
      <%= yield %>
    </body>
  </div>
</html>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <div class="form-group row">
    <%= form.label :vehicle_name, class: 'col-md-2 col-form-label' %>
    <%= form.text_field :vehicle_name, class: 'form-control col-md-4' %>
    <%= form.submit class: 'btn btn-dark mx-auto' %>
  </div>

<% end %>

app/views/vehicles/edit.html.erb
<br>

<div class="container-fluid">

    <h1 class="d-flex justify-content-center">Editing Vehicle</h1>

    <%= render 'form', vehicle: @vehicle %>

    <!--<%= link_to 'Show', @vehicle %> |
    <%= link_to 'Back', vehicles_path %>-->

    <br>

    <%= link_to vehicles_path, class: 'btn btn-light btn-large rounded-circle' do %>
        <i class="material-icons">arrow_back_ios</i> <% end %>
        
</div>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1 class="d-flex justify-content-center">Vehicles</h1>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Vehicle name</th>
        <th colspan="3">Options</th>
      </tr>
    </thead>

    <tbody>
      <% @vehicles.each do |vehicle| %>
        <tr>
          <td class="align-middle"><%= vehicle.vehicle_name %></td>
          <!--<td><%= link_to 'Show', vehicle %></td>
          <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
          <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          <td class="align-middle"><%= link_to edit_vehicle_path(vehicle), class: 'btn btn-light btn-sm rounded-circle' do %> 
            <i class="material-icons">edit</i> <% end %></td>
          <td class="align-middle"><%= link_to vehicle, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light btn-sm rounded-circle' do %>
            <i class="material-icons">delete</i> <% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Vehicle', new_vehicle_path, class: 'btn btn-dark float-right', style: 'color:white' %>
</div>

app/views/vehicles/new.html.erb
<br>

<div class="container-fluid">

    <h1 class="d-flex justify-content-center">New Vehicle</h1>

    <%= render 'form', vehicle: @vehicle %>

    <!--<%= link_to 'Back', vehicles_path %>-->

    <br>

    <%= link_to vehicles_path, class: 'btn btn-light btn-large rounded-circle' do %>
        <i class="material-icons">arrow_back_ios</i> <% end %>

</div>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle name:</strong>
  <%= @vehicle.vehicle_name %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>

app/views/waypoints/_form.html.erb
<%= form_with(model: waypoint, local: true) do |form| %>
  <% if waypoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(waypoint.errors.count, "error") %> prohibited this waypoint from being saved:</h2>

      <ul>
      <% waypoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container-fluid">
  <br>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :latitude %>
      <%= form.text_field :latitude, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :longitude %>
      <%= form.text_field :longitude, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :sent_at %>
      <div class="col-md-12 px-0"><%= form.datetime_select :sent_at %></div>
      <!--<%= form.text_field :sent_at, class: 'form-control' , type: 'datetime-local', value: 'sent_at' %>-->
    </div>
    <div class="form-group col-md-6">
      <%= form.label :vehicle_id %>
      <!--<%= form.number_field :vehicle_id %>-->
      <%= collection_select(:waypoint, :vehicle_id, @vehicles, :id, :vehicle_name, {:prompt => false}, class: 'form-control')  %>
    </div>
  </div>
  
  <br>
  
  <div class="actions">
    <%= form.submit class: 'btn btn-dark float-right', style: 'color:white'%>
  </div>

</div>
<% end %>

app/views/waypoints/edit.html.erb
<br>

<div class="container-fluid">

    <h1 class="d-flex justify-content-center">Editing Waypoint</h1>

    <%= render 'form', waypoint: @waypoint %>

    <!--<%= link_to 'Show', @waypoint %> |
    <%= link_to 'Back', waypoints_path %>-->

    <!--<%= link_to @waypoint, class: 'btn btn-light btn-large rounded-circle' do %>
        <i class="material-icons">remove_red_eye</i> <% end %>-->
    <%= link_to waypoints_path, class: 'btn btn-light btn-large rounded-circle' do %>
        <i class="material-icons">arrow_back_ios</i> <% end %>

</div>

app/views/waypoints/index.html.erb
<script>
  var json = JSON.parse(response.body);
  console.log(json);
</script>

<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1 class="d-flex justify-content-center">Waypoints</h1>

  <br>
  
  <table class="table">
    <thead class="thead-dark">
      <tr class="align-middle">
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Sent at</th>
        <th>Vehicle</th>
        <th colspan="3">Options</th>
      </tr>
    </thead>

    <tbody>
      <% @waypoints.each do |waypoint| %>
        <tr>
          <td class="align-middle"><%= waypoint.latitude %></td>
          <td class="align-middle"><%= waypoint.longitude %></td>
          <td class="align-middle"><%= waypoint.sent_at %></td>
          <td class="align-middle"><%= waypoint.vehicle.vehicle_name %></td>
          <td class="align-middle"><%= link_to waypoint, class: 'btn btn-light btn-sm rounded-circle' do %> 
            <i class="material-icons">remove_red_eye</i> <% end %></td>
          <!--<td class="align-middle"><%= link_to edit_waypoint_path(waypoint), class: 'btn btn-light btn-sm rounded-circle' do %> 
            <i class="material-icons">edit</i> <% end %></td>-->
          <td class="align-middle"><%= link_to waypoint, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light btn-sm rounded-circle' do %>
            <i class="material-icons">delete</i> <% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
<div>

app/views/waypoints/new.html.erb
<br>

<div class="container-fluid">

    <h1 class="d-flex justify-content-center">New Waypoint</h1>

    <%= render 'form', waypoint: @waypoint %>

    <!--<%= link_to 'Back', waypoints_path %>-->
    <%= link_to waypoints_path, class: 'btn btn-light btn-large rounded-circle' do %>
        <i class="material-icons">arrow_back_ios</i> <% end %>

</div>

app/views/waypoints/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1 class="d-flex justify-content-center"><%= @waypoint.vehicle.vehicle_name %></h1>

  <br>

  <div class="container">
    <div class="row">
      <div class="col-sm">
        <strong>Latitude:</strong>
        <%= @waypoint.latitude %>
      </div>
      <div class="col-sm">
        <strong>Longitude:</strong>
        <%= @waypoint.longitude %>
      </div>
      <div class="col-sm">
        <strong>Sent at:</strong>
        <%= @waypoint.sent_at %>
      </div>
      <!--<div class="col-sm">
        <strong>Vehicle:</strong>
        <%= @waypoint.vehicle.vehicle_name %>
      </div>-->
    </div>
  </div>
  
  <br>

  <p id="map" style="height: 450px;"></p>

  <!--<%= link_to 'Edit', edit_waypoint_path(@waypoint) %> |
  <%= link_to 'Back', waypoints_path %>-->

  <!--<%= link_to edit_waypoint_path(@waypoint), class: 'btn btn-light btn-large rounded-circle' do %>
    <i class="material-icons">edit</i> <% end %>-->
  <%= link_to waypoints_path, class: 'btn btn-light btn-large rounded-circle' do %>
    <i class="material-icons">arrow_back_ios</i> <% end %>
</div>

<script type="text/javascript">

  var longitude = <%= @waypoint.longitude %>;
  var latitude = <%= @waypoint.latitude %>;
  //console.log(longitude); console.log(latitude);

  //Setting up the map
  var map = new ol.Map({
    target: 'map',
    layers: [ new ol.layer.Tile({ source: new ol.source.OSM() }) ],
    view: new ol.View({
      //center: ol.proj.fromLonLat([-70.656028, -33.444592]),
      center: ol.proj.fromLonLat([longitude, latitude]),
      zoom: 17 
      }) 
  });
  //Setting location of marker
  var marker = new ol.Feature({
    geometry: new ol.geom.Point(
      //ol.proj.fromLonLat([-70.656028, -33.444592])
      ol.proj.fromLonLat([longitude, latitude])
    ),
  });
  //Styling marker
  var icon = new ol.style.Icon({
      src: 'https://png.pngtree.com/svg/20170217/9300c0869c.svg',
      anchor: [0.5, 0.5],
      scale: 0.10,
  });
  marker.setStyle(new ol.style.Style({ image: icon }));
  var vectorSource = new ol.source.Vector({ features: [marker] });
  var markerVectorLayer = new ol.layer.Vector({ source: vectorSource, });
  map.addLayer(markerVectorLayer);
</script>